import { FlatList, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { layoutTokens } from "@/constants/design-tokens";
import { useColors } from "@/hooks/use-colors";
import type { Vehicle, VehicleId } from "@/src/domain/models";
import { useState } from "react";

export function VehicleSelector({ label, helperText, vehicles = [], activeVehicleId = null, onSelectVehicle, onManageVehicles, onPress, disabled = false }: { label: string; helperText: string; vehicles?: readonly Vehicle[]; activeVehicleId?: VehicleId | null; onSelectVehicle?: (id: VehicleId) => void; onManageVehicles?: () => void; onPress?: () => void; disabled?: boolean }) {
  const colors = useColors();
  const [visible, setVisible] = useState(false);
  const isInteractive = !disabled && (onPress !== undefined || onSelectVehicle !== undefined || onManageVehicles !== undefined);
  const open = () => {
    if (onPress) onPress();
    else if (vehicles.length > 0 || onManageVehicles) setVisible(true);
  };
  return <>
    <Pressable accessibilityRole="button" accessibilityLabel="Select vehicle" accessibilityHint={helperText} accessibilityState={{ disabled: !isInteractive }} disabled={!isInteractive} onPress={open} style={({ pressed }) => [styles.selector, { borderColor: colors.border, backgroundColor: colors.surface }, pressed && isInteractive && styles.pressed, !isInteractive && styles.disabled]}><View style={[styles.icon, { backgroundColor: `${colors.primary}16` }]}><IconSymbol name="car.fill" size={20} color={colors.primary} /></View><View style={styles.copy}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><Text style={[styles.helper, { color: colors.muted }]}>{helperText}</Text></View><IconSymbol name="chevron.down" size={20} color={colors.muted} /></Pressable>
    <Modal visible={visible} transparent animationType="slide" onRequestClose={() => setVisible(false)}>
      <View style={styles.backdrop}><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><Text accessibilityRole="header" style={[styles.sheetTitle, { color: colors.foreground }]}>Choose vehicle</Text><FlatList data={vehicles} keyExtractor={(vehicle) => vehicle.id} ListEmptyComponent={<Text style={[styles.empty, { color: colors.muted }]}>Add a vehicle before recording care activity.</Text>} renderItem={({ item }) => { const selected = item.id === activeVehicleId; return <Pressable accessibilityRole="radio" accessibilityLabel={`${item.nickname}, ${item.make} ${item.model}`} accessibilityState={{ selected }} onPress={() => { onSelectVehicle?.(item.id); setVisible(false); }} style={({ pressed }) => [styles.vehicleRow, { borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? `${colors.primary}12` : colors.surface }, pressed && styles.pressed]}><View style={styles.copy}><Text style={[styles.rowTitle, { color: colors.foreground }]}>{item.nickname}</Text><Text style={[styles.helper, { color: colors.muted }]}>{item.make} {item.model} · {item.year}</Text></View>{selected ? <Text style={[styles.active, { color: colors.primary }]}>Active</Text> : null}</Pressable>; }} contentContainerStyle={styles.list} /><Pressable accessibilityRole="button" accessibilityLabel="Manage vehicles" onPress={() => { setVisible(false); onManageVehicles?.(); }} style={({ pressed }) => [styles.manage, { borderColor: colors.border }, pressed && styles.pressed]}><Text style={[styles.manageText, { color: colors.primary }]}>Manage vehicles</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Close vehicle picker" onPress={() => setVisible(false)} style={({ pressed }) => [styles.close, pressed && styles.pressed]}><Text style={[styles.manageText, { color: colors.muted }]}>Close</Text></Pressable></View></View>
    </Modal>
  </>;
}
const styles = StyleSheet.create({ selector: { minHeight: 68, borderWidth: 1, borderRadius: layoutTokens.radius.lg, padding: layoutTokens.spacing.sm, flexDirection: "row", alignItems: "center", gap: 10 }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 2 }, label: { fontSize: 16, fontWeight: "800" }, helper: { fontSize: 13, lineHeight: 18 }, pressed: { opacity: 0.74 }, disabled: { opacity: 0.74 }, backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(15, 23, 42, 0.45)" }, sheet: { maxHeight: "80%", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: layoutTokens.spacing.md, gap: layoutTokens.spacing.sm }, handle: { alignSelf: "center", width: 42, height: 4, borderRadius: 3 }, sheetTitle: { fontSize: 20, fontWeight: "800" }, list: { gap: 8, paddingVertical: 4 }, vehicleRow: { minHeight: 64, padding: layoutTokens.spacing.sm, borderWidth: 1, borderRadius: layoutTokens.radius.md, flexDirection: "row", alignItems: "center", gap: 8 }, rowTitle: { fontSize: 16, fontWeight: "800" }, active: { fontSize: 13, fontWeight: "800" }, empty: { paddingVertical: layoutTokens.spacing.lg, fontSize: 15, lineHeight: 22, textAlign: "center" }, manage: { minHeight: layoutTokens.touchTarget, borderWidth: 1, borderRadius: layoutTokens.radius.md, alignItems: "center", justifyContent: "center" }, close: { minHeight: layoutTokens.touchTarget, alignItems: "center", justifyContent: "center" }, manageText: { fontSize: 15, fontWeight: "800" } });
