import type { ComponentProps, ReactNode } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { layoutTokens } from "@/constants/design-tokens";
import { useColors } from "@/hooks/use-colors";
import { VclButton } from "@/components/ui/vcl-button";
import { VclCard } from "@/components/ui/vcl-card";

type IconName = ComponentProps<typeof IconSymbol>["name"];
type Tone = "info" | "success" | "warning" | "error";
export function StatusBanner({ tone = "info", title, message }: { tone?: Tone; title: string; message: string }) {
  const colors = useColors(); const color = tone === "success" ? colors.success : tone === "warning" ? colors.warning : tone === "error" ? colors.error : colors.primary; const icon: IconName = tone === "success" ? "car.fill" : tone === "warning" || tone === "error" ? "exclamationmark.triangle.fill" : "bell.fill";
  return <View accessible accessibilityRole={tone === "error" ? "alert" : "summary"} accessibilityLabel={`${title}. ${message}`} accessibilityLiveRegion="polite" style={[styles.banner, { borderColor: color, backgroundColor: colors.surface }]}><IconSymbol name={icon} size={18} color={color} /><View style={styles.bannerCopy}><Text style={[styles.bannerTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.bannerMessage, { color: colors.muted }]}>{message}</Text></View></View>;
}
export function EmptyState({ icon = "car.fill", title, message, actionLabel, onAction }: { icon?: IconName; title: string; message: string; actionLabel?: string; onAction?: () => void }) {
  const colors = useColors(); return <View accessible accessibilityRole="summary" accessibilityLabel={`${title}. ${message}`} style={[styles.centered, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={[styles.iconCircle, { backgroundColor: `${colors.primary}16` }]}><IconSymbol name={icon} size={28} color={colors.primary} /></View><Text style={[styles.emptyTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.emptyMessage, { color: colors.muted }]}>{message}</Text>{actionLabel && onAction ? <View style={styles.emptyAction}><VclButton label={actionLabel} onPress={onAction} icon="plus.circle.fill" /></View> : null}</View>;
}
export function LoadingState({ label = "Loading Vehicle Care Log" }: { label?: string }) { const colors = useColors(); return <View accessible accessibilityRole="progressbar" accessibilityLabel={label} accessibilityLiveRegion="polite" style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={[styles.loadingText, { color: colors.muted }]}>{label}</Text></View>; }
export function InlineError({ message }: { message: string }) { const colors = useColors(); return <View accessible accessibilityRole="alert" accessibilityLabel={message} accessibilityLiveRegion="assertive" style={[styles.inlineError, { borderColor: colors.error }]}><IconSymbol name="exclamationmark.triangle.fill" size={18} color={colors.error} /><Text style={[styles.inlineErrorText, { color: colors.error }]}>{message}</Text></View>; }
export function ConfirmationSurface({ title, message, children }: { title: string; message: string; children: ReactNode }) { const colors = useColors(); return <VclCard><Text style={[styles.confirmTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.confirmMessage, { color: colors.muted }]}>{message}</Text><View style={styles.confirmActions}>{children}</View></VclCard>; }
const styles = StyleSheet.create({ banner: { flexDirection: "row", gap: 10, borderLeftWidth: 3, borderRadius: layoutTokens.radius.md, padding: layoutTokens.spacing.sm }, bannerCopy: { flex: 1, gap: 2 }, bannerTitle: { fontSize: 14, fontWeight: "700" }, bannerMessage: { fontSize: 13, lineHeight: 18 }, centered: { alignItems: "center", borderWidth: StyleSheet.hairlineWidth, borderRadius: layoutTokens.radius.lg, padding: layoutTokens.spacing.xl, gap: 10 }, iconCircle: { width: 56, height: 56, borderRadius: 28, alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: layoutTokens.typography.heading, fontWeight: "800", textAlign: "center" }, emptyMessage: { fontSize: layoutTokens.typography.label, lineHeight: 20, textAlign: "center" }, emptyAction: { alignSelf: "stretch", marginTop: 6 }, loading: { minHeight: 140, alignItems: "center", justifyContent: "center", gap: 12 }, loadingText: { fontSize: 14 }, inlineError: { flexDirection: "row", gap: 8, alignItems: "flex-start", borderLeftWidth: 3, padding: layoutTokens.spacing.sm }, inlineErrorText: { flex: 1, fontSize: 13, lineHeight: 18 }, confirmTitle: { fontSize: layoutTokens.typography.heading, fontWeight: "800" }, confirmMessage: { marginTop: 6, fontSize: layoutTokens.typography.label, lineHeight: 20 }, confirmActions: { marginTop: layoutTokens.spacing.md, gap: layoutTokens.spacing.xs } });
